### ISSUE TITLE
Launcher --access_token option doesn't appear to work

### ISSUE THREAD

**Issue by avillela** [lightstep/otel-launcher-python#115]
**Describe the bug**
Some of the flags documented in the [Python Launcher Readme](https://github.com/lightstep/otel-launcher-python#usage-with-auto-instrumentation) are incorrect.

**To Reproduce**
Tried to follow the Auto-Instrumentation instructions in the [Python Launcher Readme](https://github.com/lightstep/otel-launcher-python#usage-with-auto-instrumentation). I didn't want to pass the Lightstep token as an env var, and instead wanted to use the command-line option, `access_token`, which is listed in the readme.

```bash
opentelemetry-instrument \
    --access_token ${LS_ACCESS_TOKEN} \
    python server_uninstrumented.py
```

**Expected behavior**
Send OTel data to Lightstep

**Actual behavior**

Got this error when I tried to run `opentelemetry-instrument`:

```
opentelemetry-instrument: error: unrecognized arguments: --access_token
```

**Comment by ocelotl** [comment]
`access_token` is not a command line option, closing.
