### ISSUE TITLE
Please update to support opentelemetry-instrumentation 0.38b0

### ISSUE THREAD

**Issue by andrewthetechie** [lightstep/otel-launcher-python#146]
**Is your feature request related to a problem? Please describe.**
https://pypi.org/project/opentelemetry-instrumentation/0.38b0/

0.38b0 was released on March 22 and has some fixes for bugs around urllib3 

**Describe the solution you'd like**
A new version of opentelemetry-launcher released that supports opentelemetry-instrumentation 0.38b0

**Describe alternatives you've considered**
None

**Comment by codeboten** [comment]
This has now been released: https://pypi.org/project/opentelemetry-launcher/1.14.0/

Thanks for your help @andrewthetechie!

**Comment by andrewthetechie** [comment]
Thank you!
