### ISSUE TITLE
opentelemetry(launcher) installation fails..

### ISSUE THREAD

**Issue by raghavancgn** [lightstep/otel-launcher-python#67]
I am trying to install OT on another system. (Pl also refer to my previous observation filed earlier). But it erred with compilation error. Required packages seem to be in place..

centos-2gb-hel1-2 openTelemetry]# pip3 install opentelemetry-launcher
Collecting opentelemetry-launcher
Using cached opentelemetry_launcher-0.15b0-py3-none-any.whl (14 kB)
Requirement already satisfied: opentelemetry-api==0.15b0 in ./new_virtual_environment/lib/python3.6/site-packages (from opentelemetry-launcher) (0.15b0)
Requirement already satisfied: environs>=8.0.0 in ./new_virtual_environment/lib/python3.6/site-packages (from opentelemetry-launcher) (9.3.0)
Requirement already satisfied: aiocontextvars in ./new_virtual_environment/lib/python3.6/site-packages (from opentelemetry-api==0.15b0->opentelemetry-launcher) (0.2.2)
Collecting opentelemetry-exporter-otlp==0.15b0
Using cached opentelemetry_exporter_otlp-0.15b0-py3-none-any.whl (15 kB)
Requirement already satisfied: googleapis-common-protos~=1.52.0 in ./new_virtual_environment/lib/python3.6/site-packages (from opentelemetry-exporter-otlp==0.15b0->opentelemetry-launcher) (1.52.0)
Requirement already satisfied: backoff~=1.10.0 in ./new_virtual_environment/lib/python3.6/site-packages (from opentelemetry-exporter-otlp==0.15b0->opentelemetry-launcher) (1.10.0)
Requirement already satisfied: grpcio<2.0.0,>=1.0.0 in ./new_virtual_environment/lib/python3.6/site-packages (from opentelemetry-exporter-otlp==0.15b0->opentelemetry-launcher) (1.34.0)
Collecting opentelemetry-instrumentation==0.15b0
Using cached opentelemetry_instrumentation-0.15b0-py3-none-any.whl (11 kB)
Requirement already satisfied: wrapt<2.0.0,>=1.0.0 in ./new_virtual_environment/lib/python3.6/site-packages (from opentelemetry-instrumentation==0.15b0->opentelemetry-launcher) (1.12.1)
Collecting opentelemetry-instrumentation-system-metrics==0.15b0
Using cached opentelemetry_instrumentation_system_metrics-0.15b0-py3-none-any.whl (10 kB)
Collecting opentelemetry-proto==0.15b0
Using cached opentelemetry_proto-0.15b0-py3-none-any.whl (50 kB)
Requirement already satisfied: protobuf~=3.12.2 in ./new_virtual_environment/lib/python3.6/site-packages (from opentelemetry-proto==0.15b0->opentelemetry-exporter-otlp==0.15b0->opentelemetry-launcher) (3.12.4)
Collecting opentelemetry-sdk==0.15b0
Using cached opentelemetry_sdk-0.15b0-py3-none-any.whl (45 kB)
Requirement already satisfied: python-dotenv in ./new_virtual_environment/lib/python3.6/site-packages (from environs>=8.0.0->opentelemetry-launcher) (0.15.0)
Requirement already satisfied: marshmallow>=2.7.0 in ./new_virtual_environment/lib/python3.6/site-packages (from environs>=8.0.0->opentelemetry-launcher) (3.10.0)
Requirement already satisfied: six>=1.5.2 in ./new_virtual_environment/lib/python3.6/site-packages (from grpcio<2.0.0,>=1.0.0->opentelemetry-exporter-otlp==0.15b0->opentelemetry-launcher) (1.15.0)
Requirement already satisfied: setuptools in ./new_virtual_environment/lib/python3.6/site-packages (from protobuf~=3.12.2->opentelemetry-proto==0.15b0->opentelemetry-exporter-otlp==0.15b0->opentelemetry-launcher) (39.2.0)
Collecting psutil~=5.7.0
Using cached psutil-5.7.3.tar.gz (465 kB)
Requirement already satisfied: contextvars==2.4 in ./new_virtual_environment/lib/python3.6/site-packages (from aiocontextvars->opentelemetry-api==0.15b0->opentelemetry-launcher) (2.4)
Requirement already satisfied: immutables>=0.9 in ./new_virtual_environment/lib/python3.6/site-packages (from contextvars==2.4->aiocontextvars->opentelemetry-api==0.15b0->opentelemetry-launcher) (0.14)
Building wheels for collected packages: psutil
Building wheel for psutil (setup.py) ... error
ERROR: Command errored out with exit status 1:
command: /root/thoughtdata/raghavan/openTelemetry/new_virtual_environment/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-6bt0y2ca/psutil_8a1d6fd4d4474948a7715298587d7eb0/setup.py'"'"'; __file__='"'"'/tmp/pip-install-6bt0y2ca/psutil_8a1d6fd4d4474948a7715298587d7eb0/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-2m1bunwh
cwd: /tmp/pip-install-6bt0y2ca/psutil_8a1d6fd4d4474948a7715298587d7eb0/
Complete output (45 lines):
running bdist_wheel
running build
running build_py
creating build
creating build/lib.linux-x86_64-3.6
creating build/lib.linux-x86_64-3.6/psutil
copying psutil/_pswindows.py -> build/lib.linux-x86_64-3.6/psutil
copying psutil/_psaix.py -> build/lib.linux-x86_64-3.6/psutil
copying psutil/_pssunos.py -> build/lib.linux-x86_64-3.6/psutil
copying psutil/__init__.py -> build/lib.linux-x86_64-3.6/psutil
copying psutil/_common.py -> build/lib.linux-x86_64-3.6/psutil
copying psutil/_psposix.py -> build/lib.linux-x86_64-3.6/psutil
copying psutil/_psosx.py -> build/lib.linux-x86_64-3.6/psutil
copying psutil/_psbsd.py -> build/lib.linux-x86_64-3.6/psutil
copying psutil/_compat.py -> build/lib.linux-x86_64-3.6/psutil
copying psutil/_pslinux.py -> build/lib.linux-x86_64-3.6/psutil
creating build/lib.linux-x86_64-3.6/psutil/tests
copying psutil/tests/test_unicode.py -> build/lib.linux-x86_64-3.6/psutil/tests
copying psutil/tests/test_testutils.py -> build/lib.linux-x86_64-3.6/psutil/tests
copying psutil/tests/__init__.py -> build/lib.linux-x86_64-3.6/psutil/tests
copying psutil/tests/test_windows.py -> build/lib.linux-x86_64-3.6/psutil/tests
copying psutil/tests/test_posix.py -> build/lib.linux-x86_64-3.6/psutil/tests
copying psutil/tests/test_system.py -> build/lib.linux-x86_64-3.6/psutil/tests
copying psutil/tests/test_sunos.py -> build/lib.linux-x86_64-3.6/psutil/tests
copying psutil/tests/test_connections.py -> build/lib.linux-x86_64-3.6/psutil/tests
copying psutil/tests/test_osx.py -> build/lib.linux-x86_64-3.6/psutil/tests
copying psutil/tests/test_bsd.py -> build/lib.linux-x86_64-3.6/psutil/tests
copying psutil/tests/test_misc.py -> build/lib.linux-x86_64-3.6/psutil/tests
copying psutil/tests/test_aix.py -> build/lib.linux-x86_64-3.6/psutil/tests
copying psutil/tests/test_linux.py -> build/lib.linux-x86_64-3.6/psutil/tests
copying psutil/tests/test_contracts.py -> build/lib.linux-x86_64-3.6/psutil/tests
copying psutil/tests/__main__.py -> build/lib.linux-x86_64-3.6/psutil/tests
copying psutil/tests/test_process.py -> build/lib.linux-x86_64-3.6/psutil/tests
copying psutil/tests/runner.py -> build/lib.linux-x86_64-3.6/psutil/tests
copying psutil/tests/test_memleaks.py -> build/lib.linux-x86_64-3.6/psutil/tests
running build_ext
building 'psutil._psutil_linux' extension
creating build/temp.linux-x86_64-3.6
creating build/temp.linux-x86_64-3.6/psutil
gcc -pthread -Wno-unused-result -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -fPIC -DPSUTIL_POSIX=1 -DPSUTIL_SIZEOF_PID_T=4 -DPSUTIL_VERSION=573 -DPSUTIL_LINUX=1 -I/root/thoughtdata/raghavan/openTelemetry/new_virtual_environment/include -I/usr/include/python3.6m -c psutil/_psutil_common.c -o build/temp.linux-x86_64-3.6/psutil/_psutil_common.o
psutil/_psutil_common.c:9:10: fatal error: Python.h: No such file or directory
#include <Python.h>
^~~~~~~~~~
compilation terminated.
error: command 'gcc' failed with exit status 1
----------------------------------------
ERROR: Failed building wheel for psutil
Running setup.py clean for psutil
Failed to build psutil
Installing collected packages: psutil, opentelemetry-sdk, opentelemetry-proto, opentelemetry-instrumentation-system-metrics, opentelemetry-instrumentation, opentelemetry-exporter-otlp, opentelemetry-launcher
Attempting uninstall: psutil
Found existing installation: psutil 5.8.0
Uninstalling psutil-5.8.0:
Successfully uninstalled psutil-5.8.0
Running setup.py install for psutil ... error
ERROR: Command errored out with exit status 1:
command: /root/thoughtdata/raghavan/openTelemetry/new_virtual_environment/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-6bt0y2ca/psutil_8a1d6fd4d4474948a7715298587d7eb0/setup.py'"'"'; __file__='"'"'/tmp/pip-install-6bt0y2ca/psutil_8a1d6fd4d4474948a7715298587d7eb0/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-ln7whi41/install-record.txt --single-version-externally-managed --compile --install-headers /root/thoughtdata/raghavan/openTelemetry/new_virtual_environment/include/site/python3.6/psutil
cwd: /tmp/pip-install-6bt0y2ca/psutil_8a1d6fd4d4474948a7715298587d7eb0/
Complete output (45 lines):
running install
running build
running build_py
creating build
creating build/lib.linux-x86_64-3.6
creating build/lib.linux-x86_64-3.6/psutil
copying psutil/_pswindows.py -> build/lib.linux-x86_64-3.6/psutil
copying psutil/_psaix.py -> build/lib.linux-x86_64-3.6/psutil
copying psutil/_pssunos.py -> build/lib.linux-x86_64-3.6/psutil
copying psutil/__init__.py -> build/lib.linux-x86_64-3.6/psutil
copying psutil/_common.py -> build/lib.linux-x86_64-3.6/psutil
copying psutil/_psposix.py -> build/lib.linux-x86_64-3.6/psutil
copying psutil/_psosx.py -> build/lib.linux-x86_64-3.6/psutil
copying psutil/_psbsd.py -> build/lib.linux-x86_64-3.6/psutil
copying psutil/_compat.py -> build/lib.linux-x86_64-3.6/psutil
copying psutil/_pslinux.py -> build/lib.linux-x86_64-3.6/psutil
creating build/lib.linux-x86_64-3.6/psutil/tests
copying psutil/tests/test_unicode.py -> build/lib.linux-x86_64-3.6/psutil/tests
copying psutil/tests/test_testutils.py -> build/lib.linux-x86_64-3.6/psutil/tests
copying psutil/tests/__init__.py -> build/lib.linux-x86_64-3.6/psutil/tests
copying psutil/tests/test_windows.py -> build/lib.linux-x86_64-3.6/psutil/tests
copying psutil/tests/test_posix.py -> build/lib.linux-x86_64-3.6/psutil/tests
copying psutil/tests/test_system.py -> build/lib.linux-x86_64-3.6/psutil/tests
copying psutil/tests/test_sunos.py -> build/lib.linux-x86_64-3.6/psutil/tests
copying psutil/tests/test_connections.py -> build/lib.linux-x86_64-3.6/psutil/tests
copying psutil/tests/test_osx.py -> build/lib.linux-x86_64-3.6/psutil/tests
copying psutil/tests/test_bsd.py -> build/lib.linux-x86_64-3.6/psutil/tests
copying psutil/tests/test_misc.py -> build/lib.linux-x86_64-3.6/psutil/tests
copying psutil/tests/test_aix.py -> build/lib.linux-x86_64-3.6/psutil/tests
copying psutil/tests/test_linux.py -> build/lib.linux-x86_64-3.6/psutil/tests
copying psutil/tests/test_contracts.py -> build/lib.linux-x86_64-3.6/psutil/tests
copying psutil/tests/__main__.py -> build/lib.linux-x86_64-3.6/psutil/tests
copying psutil/tests/test_process.py -> build/lib.linux-x86_64-3.6/psutil/tests
copying psutil/tests/runner.py -> build/lib.linux-x86_64-3.6/psutil/tests
copying psutil/tests/test_memleaks.py -> build/lib.linux-x86_64-3.6/psutil/tests
running build_ext
building 'psutil._psutil_linux' extension
creating build/temp.linux-x86_64-3.6
creating build/temp.linux-x86_64-3.6/psutil
gcc -pthread -Wno-unused-result -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -fPIC -DPSUTIL_POSIX=1 -DPSUTIL_SIZEOF_PID_T=4 -DPSUTIL_VERSION=573 -DPSUTIL_LINUX=1 -I/root/thoughtdata/raghavan/openTelemetry/new_virtual_environment/include -I/usr/include/python3.6m -c psutil/_psutil_common.c -o build/temp.linux-x86_64-3.6/psutil/_psutil_common.o
psutil/_psutil_common.c:9:10: fatal error: Python.h: No such file or directory
#include <Python.h>
^~~~~~~~~~
compilation terminated.
error: command 'gcc' failed with exit status 1
----------------------------------------
Rolling back uninstall of psutil
Moving to /root/thoughtdata/raghavan/openTelemetry/new_virtual_environment/lib/python3.6/site-packages/psutil-5.8.0.dist-info/
from /root/thoughtdata/raghavan/openTelemetry/new_virtual_environment/lib/python3.6/site-packages/~sutil-5.8.0.dist-info
Moving to /root/thoughtdata/raghavan/openTelemetry/new_virtual_environment/lib/python3.6/site-packages/psutil/
from /root/thoughtdata/raghavan/openTelemetry/new_virtual_environment/lib/python3.6/site-packages/~sutil
ERROR: Command errored out with exit status 1: /root/thoughtdata/raghavan/openTelemetry/new_virtual_environment/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-6bt0y2ca/psutil_8a1d6fd4d4474948a7715298587d7eb0/setup.py'"'"'; __file__='"'"'/tmp/pip-install-6bt0y2ca/psutil_8a1d6fd4d4474948a7715298587d7eb0/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-ln7whi41/install-record.txt --single-version-externally-managed --compile --install-headers /root/thoughtdata/raghavan/openTelemetry/new_virtual_environment/include/site/python3.6/psutil Check the logs for full command output.
(new_virtual_environment) [root@snapshot-18650712-centos-2gb-hel1-2 openTelemetry]#

**Comment by codeboten** [comment]
The launcher uses `psutil` to emit metrics, this stackoverflow query may help: https://stackoverflow.com/questions/33100812/install-latest-psutil-version-in-centos-6-7

**Comment by codeboten** [comment]
@raghavancgn can you confirm whether this issue was resolved by installing psutil?

**Comment by codeboten** [comment]
Closing for now, please re-open with more information.
